spring:
  application:
    name: taco-cloud
  datasource:
    generate-unique-name: false
    name: taco-cloud
    #    url: jdbc:h2:mem:taco-cloud
  data:
    rest:
      base-path: data-api

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_0le4G5DHH
          jwk-set-uri: https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_0le4G5DHH/.well-known/jwks.json