DELETE http://localhost:8080/api/ingredients/CRKT
Authorization: Bearer eyJraWQiOiJlOWZlNzM5Ni1hODVmLTQ3M2MtODU5OC03YmQ4NzA5NjQ3N2QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0YWNvY2hlZiIsImF1ZCI6InRhY28tYWRtaW4tY2xpZW50IiwibmJmIjoxNzU1OTI4NDYxLCJzY29wZSI6WyJkZWxldGVJbmdyZWRpZW50cyIsIndyaXRlSW5ncmVkaWVudHMiXSwiaXNzIjoiaHR0cDovLzEyNy4wLjAuMTo5MDAwIiwiZXhwIjoxNzU1OTI4NzYxLCJpYXQiOjE3NTU5Mjg0NjEsImp0aSI6Ijc0ZGVlOGYyLTQyOTgtNDBhNC05M2M1LTk2YWUwZmJjODU2NSJ9.sK7VTBxGmivNE13UvvKbZpOv7Xs0cIGZw1sLr4zXI1TzZcxEhY1dH0Oy4CEBk75Bbmv0MSzbR62QAox6v5k4AIydTDHd9WbQ5bp_IzKO7f0wy1hYvKmNewNheDpIwH3iQex3RKkYyf5Vx2kfEeRUdNDzFJOV76DjH16k_VetG2Nsi9Zu3Uevfg2tKyVL8KwTwlj2m5v1O4F_w3_tfLQjUaLxTDPVHAcsXuzRau1RivHPY_1rVJVkfhO11KBWIwa6v40TM11fK72eX8cJoqkPGGg-DHQWjB6Wv170H3e_QaDOUQdvjqggN3uH3CktP18HxZrs91bcNJpdPMe_cbi85Q