apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster

spec:
  instances: 3
  storage:
    size: 1Gi

  managed:
    roles:
      - name: app
        createdb: true
        login: true
      - name: dante
        ensure: present
        comment: my database-side comment
        login: true
        superuser: false
        createdb: true
        createrole: false
        inherit: false
        replication: false
        bypassrls: false
        connectionLimit: 4
        validUntil: "2053-04-12T15:04:05Z"
        inRoles:
          - pg_monitor
          - pg_signal_backend
        passwordSecret:
          name: postgres-secret-dante
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: postgres-secret-dante
data:
  username: ZGFudGU=
  password: ZGFudGU=

---

apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: taco-cloud-database
spec:
  name: taco-cloud
  owner: app
  cluster:
    name: postgres-cluster