apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dual-role
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 25Gi
        deleteClaim: false
        kraftMetadata: shared
---

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 4.0.0
    metadataVersion: 4.0-IV3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
#      - name: external
#        port: 9094
#        type: ingress
#        tls: true
#        configuration:
#          bootstrap:
#            host: bootstrap.192.168.64.46.nip.io
#          brokers:
#          - broker: 0
#            host: broker-0.192.168.64.46.nip.io
#      - name: external
#        port: 9094
#        type: nodeport
#        tls: false
#      - name: external
#        port: 9094
#        type: loadbalancer
#        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  entityOperator:
    topicOperator: {}
    userOperator: {}

---

#apiVersion: kafka.strimzi.io/v1beta2
#kind: KafkaTopic
#metadata:
#  name: first-topic
#  labels:
#    strimzi.io/cluster: kafka-cluster
#spec:
#  partitions: 1
#  replicas: 1